# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackit" do
  name "stackit"
  desc "A command-line interface to manage STACKIT resources.
This CLI is in a beta state. More services and functionality will be supported soon."
  homepage "https://github.com/stackitcloud/stackit-cli"
  version "0.40.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackit"
  bash_completion "./completions/stackit.bash"
  zsh_completion "./completions/stackit.zsh"
  fish_completion "./completions/stackit.fish"

  on_macos do
    on_intel do
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v#{version}/stackit-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "2f3301dce06ae065c203fcd7e66d79f68fa99b0ed0b8dfa048ff8de1af1f575e"
    end
    on_arm do
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v#{version}/stackit-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "d00e39be8c9a045c9bac408f05c4411370766653671769bccc6cdbc4733446c7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v#{version}/stackit-cli_#{version}_linux_amd64.tar.gz"
      sha256 "3537ec1a5660d22d5975e11207c50e688514bbd96474bfafae656d66ada5bacb"
    end
    on_arm do
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v#{version}/stackit-cli_#{version}_linux_arm64.tar.gz"
      sha256 "5b50c6ab7d94bf1d406616c8bccb1482f9a51c74ff88402ff3c9098cf94237cd"
    end
  end

  # No zap stanza required
end
