# This file was generated by GoReleaser. DO NOT EDIT.
cask "stackit" do
  name "stackit"
  desc "A command-line interface to manage STACKIT resources."
  homepage "https://github.com/stackitcloud/stackit-cli"
  version "0.48.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stackit"
  bash_completion "./completions/stackit.bash"
  zsh_completion "./completions/stackit.zsh"
  fish_completion "./completions/stackit.fish"

  on_macos do
    on_intel do
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v#{version}/stackit-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "719691414da81b3ac1b8de49b4b7c792bef44f7ab56f1fd0db06bf2b65ade29a"
    end
    on_arm do
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v#{version}/stackit-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "4b3070aede2f825b377c19b0ba7f9dc2e7aa692baa7b36602d10b7f47551834b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v#{version}/stackit-cli_#{version}_linux_amd64.tar.gz"
      sha256 "3818a0db30e73a785f1e9548bc47d054d2eab26626e0c95814f080b65d8f28b5"
    end
    on_arm do
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v#{version}/stackit-cli_#{version}_linux_arm64.tar.gz"
      sha256 "dc59c828a6261b478132a036347221a1afd7e5cc48fda36fb7f0a45f979138f4"
    end
  end

  # No zap stanza required
end
