# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StackitCli < Formula
  desc "A command-line interface to manage STACKIT resources."
  homepage "https://github.com/stackitcloud/stackit-cli"
  version "0.1.0-beta.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v0.1.0-beta.2/stackit-cli_Darwin_arm64.tar.gz"
      sha256 "bfb00897b63de83687694b26cb33adc5b8c53bf7ddb406c5e79523df07749785"

      def install
        bin.install "stackit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v0.1.0-beta.2/stackit-cli_Darwin_x86_64.tar.gz"
      sha256 "d95cda86711568ab9dc12e8bac25fa21a3d41946134609893eb662affbc2e373"

      def install
        bin.install "stackit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v0.1.0-beta.2/stackit-cli_Linux_arm64.tar.gz"
      sha256 "48aa0e3100ea90abf48921bb026b9fd521fa7f947cc2adb1aa25f394841ce904"

      def install
        bin.install "stackit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v0.1.0-beta.2/stackit-cli_Linux_x86_64.tar.gz"
      sha256 "4db89fd907f890e5d33589d331ae30ece3b25903a6a9aba20755c9be310fe670"

      def install
        bin.install "stackit"
      end
    end
  end
end
