# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackit < Formula
  desc "A command-line interface to manage STACKIT resources.
This CLI is in a BETA state. More services and functionality will be supported soon."
  homepage "https://github.com/stackitcloud/stackit-cli"
  version "0.1.0-apt-prerelease.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v0.1.0-apt-prerelease.3/stackit-cli_0.1.0-apt-prerelease.3_darwin_amd64.tar.gz"
      sha256 "eccae48a4b1b74ba040e504e0dc3d5ca6d772ccfd43c578ea10f625034062ca3"

      def install
        bin.install "stackit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v0.1.0-apt-prerelease.3/stackit-cli_0.1.0-apt-prerelease.3_darwin_arm64.tar.gz"
      sha256 "98347db7fb1b65ff638c341318ac476b4738755533f8f7f0a1e69e3678ad622d"

      def install
        bin.install "stackit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v0.1.0-apt-prerelease.3/stackit-cli_0.1.0-apt-prerelease.3_linux_amd64.tar.gz"
      sha256 "947ecc4180301be79ef2995f380258ece04c8eda50ee6cc5995f0c824d50c52b"

      def install
        bin.install "stackit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v0.1.0-apt-prerelease.3/stackit-cli_0.1.0-apt-prerelease.3_linux_arm64.tar.gz"
      sha256 "9cb2698bd1fd277f520a09ee489c55fc7623f1abea1df2fa84d8e7a745ac0ff1"

      def install
        bin.install "stackit"
      end
    end
  end
end
