# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StackitCli < Formula
  desc "A command-line interface to manage STACKIT resources."
  homepage "https://github.com/stackitcloud/stackit-cli"
  version "0.1.0-beta.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v0.1.0-beta.3/stackit-cli_Darwin_arm64.tar.gz"
      sha256 "bbe1fcd521cba7fd6ddfb71fcf5e83bdc63c5dd7617094a26e45aaeaa06174ea"

      def install
        bin.install "stackit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v0.1.0-beta.3/stackit-cli_Darwin_x86_64.tar.gz"
      sha256 "7fffab9f513aaadddb8b8587f5ba440edab0ff12b95773e6450fd60e0435727b"

      def install
        bin.install "stackit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v0.1.0-beta.3/stackit-cli_Linux_arm64.tar.gz"
      sha256 "64713f2516ce91a6d02e64dea830b7c58f4b9db6deea6be4ae5a32b60a3cde1a"

      def install
        bin.install "stackit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stackitcloud/stackit-cli/releases/download/v0.1.0-beta.3/stackit-cli_Linux_x86_64.tar.gz"
      sha256 "39841499bf10d26d2bbdad87390810a0e5582afe4f47f11cf80b62423de6f722"

      def install
        bin.install "stackit"
      end
    end
  end
end
